# https://github.com/kubernetes/test-infra/blob/master/prow/cmd/branchprotector/README.md
branch-protection:
  orgs:
    backube:
      repos:
        scribe:
          branches:
            master:
              protect: true
              required_status_checks:
                contexts:
                - "Build docs"
                - DCO
                - "Successful e2e tests"
                strict: true
            "release-*":
              protect: true
              required_status_checks:
                contexts:
                - "Build docs"
                - DCO
                - "Successful e2e tests"
                strict: true

tide:
  queries:
  - labels:
    - approved
    - lgtm
    missingLabels:
    - do-not-merge/hold
    - do-not-merge/invalid-owners-file
    - do-not-merge/work-in-progress
    - needs-rebase
    repos:
    - backube/scribe
